title: "Keshav Agrawal"
email: keshav97722@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Hey welcome to the world of Keshav Agrawal.
  Let's have some fun,so now be ready to go crazy with me!!
baseurl: "/" 
url: "/portfolio-template" 
twitter_username: KeshavA76309037
github_username:  Keshav04042001

sass:
  sass_dir: _sass

icon: ./assets/img/icon.jpg
